services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py

  api:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    command: celery -A tasks worker --loglevel=info

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
